name: Compilar APK Honor
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Instalar Buildozer
        run: |
          pip install --user --upgrade buildozer cython==0.29.33
          sudo apt update
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - name: Compilar con Buildozer
        run: buildozer android debug
      - name: Subir APK resultante
        uses: actions/upload-artifact@v2
        with:
          name: MiAppNotas-Honor
          path: bin/*.apk
